// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhxpgzxcxxktkdxgpdbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeHBnenhjeHhrdGtkeGdwZGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDQyNTAsImV4cCI6MjA2NTg4MDI1MH0.LHPuh9yFfS9_RK3q3fspU5oxlByoF4ilpMc_F9FeOg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);